version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - ./env/.env.frontend
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./env/.env.backend
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
