version: '3'

tasks:
  install-nix:
    desc: Install Nix package manager if not already installed
    cmds:
      - |
        if ! command -v nix &> /dev/null; then
          echo "Nix is not installed. Installing Nix..."
          curl -L https://nixos.org/nix/install | sh
          echo "Nix installed successfully. Please restart your terminal or run 'source ~/.nix-profile/etc/profile.d/nix.sh'"
        else
          echo "Nix is already installed."
        fi

  start:
    desc: Start the application stack with Docker Compose
    cmds:
      - docker-compose up --build

  stop:
    desc: Stop the Docker Compose stack
    cmds:
      - docker-compose down

  test-backend:
    desc: Run backend tests
    dir: backend
    cmds:
      - npm run test

  migration-generate:
    desc: Generate a new migration
    dir: backend
    vars:
      MIGRATION_NAME: '{{default "InitialMigration" .CLI_ARGS}}'
    cmds:
      - npm run migration:generate --name={{.MIGRATION_NAME}}

  migration-run:
    desc: Run pending migrations
    dir: backend
    cmds:
      - npm run migration:run

  migration-revert:
    desc: Revert last migration
    dir: backend
    cmds:
      - npm run migration:revert
